### PR TITLE
added sound to the game

### PR DESCRIPTION
**Pull request by hkiame**
I added some free background sound and effects. The background sound is from https://opengameart.org/content/platformer-game-music-pack while the sound effects are from https://www.zapsplat.com/sound-effect-category/game-sounds/ .

### CODE REVIEW

**Comment by melcor76** [comment]
That's awesome @hkiame! 
I have been meaning to add sound but never get around to it.
The hard drop sound is a bit annoying though after a while. :-)

**Comment by hkiame** [comment]
Thank you @melcor76 . What do you suggest i should do? Should i remove it completely or look for an alternative sound effect?

**Comment by melcor76** [comment]
@hkiame Maybe find another sound effect. It's a good sound but it should maybe happen with another event that doesn't happen as often as the hard drop. Maybe when you get a Tetris or advance an level or something? Now that you implemented the sounds we can see what sounds work best where.

**Comment by hkiame** [comment]
Sure. You are absolutely right. I will do as you have said.

**Pull request merged**
